version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: finfinity_portal_app_dev
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
      - ./certs:/etc/nginx/ssl:ro
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=https://localhost:8443
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG="client_host=host.docker.internal client_port=9003"
    depends_on:
      - db
      - redis
    networks:
      - finfinity_network

  db:
    image: postgres:15
    container_name: finfinity_portal_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: finfinity_portal_dev
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data_dev:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - finfinity_network

  redis:
    image: redis:7-alpine
    container_name: finfinity_portal_redis_dev
    restart: unless-stopped
    volumes:
      - redis_data_dev:/data
    ports:
      - "6379:6379"
    networks:
      - finfinity_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: finfinity_portal_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finfinity.co.in
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - finfinity_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: finfinity_portal_redis_commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
    networks:
      - finfinity_network

  mailhog:
    image: mailhog/mailhog
    container_name: finfinity_portal_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - finfinity_network

volumes:
  db_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  finfinity_network:
    driver: bridge 