services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finfinity_portal_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
      - ./certs:/etc/nginx/ssl:ro
    ports:
      - "3000:3000"  # Vite dev server (main app)
      - "8000:8000"  # Laravel API
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://localhost
    network_mode: "host"  # Use host network to access external services

networks:
  finfinity_network:
    driver: bridge 